export const demoProducts = [
    {
        product_id: "101",
        product_name: "Smartphone X",
        description: "A high-end smartphone with advanced features.",
        base_price: "899.99",
        discount: "10",
        unit: "piece",
        stock: "50",
        product_image: "smartphone_x.png",
        category_ids: [1, 3],
        category_names: ["Electronics", "Gadgets"],
    },
    {
        product_id: "102",
        product_name: "Fitness Tracker",
        description:
            "Track your fitness goals with this sleek wearable device.",
        base_price: "49.99",
        discount: "5",
        unit: "piece",
        stock: "30",
        product_image: "fitness_tracker.png",
        category_ids: [2, 3],
        category_names: ["Fitness", "Gadgets"],
    },
    {
        product_id: "103",
        product_name: "Coffee Maker",
        description:
            "Brew your favorite coffee with this stylish coffee maker.",
        base_price: "79.99",
        discount: "8",
        unit: "piece",
        stock: "20",
        product_image: "coffee_maker.png",
        category_ids: [1, 4],
        category_names: ["Electronics", "Home Appliances"],
    },
    {
        product_id: "104",
        product_name: "Leather Backpack",
        description: "A durable and fashionable backpack for everyday use.",
        base_price: "59.99",
        discount: "7",
        unit: "piece",
        stock: "40",
        product_image: "leather_backpack.png",
        category_ids: [5, 6],
        category_names: ["Fashion", "Accessories"],
    },
    {
        product_id: "105",
        product_name: "LED Desk Lamp",
        description: "Illuminate your workspace with adjustable LED lighting.",
        base_price: "34.99",
        discount: "6",
        unit: "piece",
        stock: "25",
        product_image: "led_desk_lamp.png",
        category_ids: [1, 4],
        category_names: ["Electronics", "Home Appliances"],
    },
    {
        product_id: "106",
        product_name: "Wireless Earbuds",
        description: "Enjoy wireless music with crystal-clear sound quality.",
        base_price: "69.99",
        discount: "12",
        unit: "pair",
        stock: "35",
        product_image: "wireless_earbuds.png",
        category_ids: [1, 3],
        category_names: ["Electronics", "Gadgets"],
    },
    {
        product_id: "107",
        product_name: "Portable Blender",
        description:
            "Blend your favorite smoothies on the go with this portable device.",
        base_price: "39.99",
        discount: "5",
        unit: "piece",
        stock: "15",
        product_image: "portable_blender.png",
        category_ids: [2, 4],
        category_names: ["Fitness", "Home Appliances"],
    },
    {
        product_id: "108",
        product_name: "Digital Camera",
        description:
            "Capture stunning moments with this high-resolution digital camera.",
        base_price: "499.99",
        discount: "15",
        unit: "piece",
        stock: "10",
        product_image: "digital_camera.png",
        category_ids: [1, 3],
        category_names: ["Electronics", "Gadgets"],
    },
    {
        product_id: "109",
        product_name: "Gaming Mouse",
        description:
            "Enhance your gaming experience with a precision gaming mouse.",
        base_price: "49.99",
        discount: "8",
        unit: "piece",
        stock: "20",
        product_image: "gaming_mouse.png",
        category_ids: [1, 7],
        category_names: ["Electronics", "Gaming"],
    },
    {
        product_id: "110",
        product_name: "Stainless Steel Water Bottle",
        description:
            "Stay hydrated with this durable and stylish water bottle.",
        base_price: "19.99",
        discount: "4",
        unit: "piece",
        stock: "30",
        product_image: "water_bottle.png",
        category_ids: [2, 6],
        category_names: ["Fitness", "Accessories"],
    },
    {
        product_id: "111",
        product_name: "Smart Thermostat",
        description:
            "Control your home's temperature smartly with this thermostat.",
        base_price: "129.99",
        discount: "10",
        unit: "piece",
        stock: "15",
        product_image: "smart_thermostat.png",
        category_ids: [1, 4],
        category_names: ["Electronics", "Home Appliances"],
    },
    {
        product_id: "112",
        product_name: "Organic Bamboo Bed Sheets",
        description:
            "Experience luxury and comfort with these eco-friendly bed sheets.",
        base_price: "79.99",
        discount: "6",
        unit: "set",
        stock: "25",
        product_image: "bamboo_bed_sheets.png",
        category_ids: [4, 6],
        category_names: ["Home & Living", "Accessories"],
    },
];
